apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-python-webapp
  name: hello-python-webapp
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: amitvashist7/mypython-web-app:v3
    name: hello-python-webapp
    ports:
    - containerPort: 8081
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
